commands_typos = {
    "dialog": ["dialo", "dialogs"],
    "charslot": ["charslsot"],
    "musicvolume": ["musicvolune"],
    "stopmusic": ["stopmucis"],
    "playsound": ["palysound"],
    "delay": ["dealy", "delau", "daley", "delayt", "delat"],
}

useless_commands = [
    "header",
    "chaa",
    "warp",
    "skipnode",
    "skiptothis",
    "duration",
    "startbattle",
    "tutorial",
    "gotopage",
]

stripped_useless_commands = [
    "spellsticker",
    "spellstickerclear",
    "timersticker",
    "timerclear",
    "interlude",
    "imagetween",
    "backgroundtween",
    "largebgtween",
    "characteraction",
    "imagerotate",
    "imgeffect",
    "delay",
    "theater",
    "avgdisplay",
    "camerashake",
    "effect",
    "soundvolume",
    "musicvolume",
    "focusparam",
    "focusout",
    "curtain",
]

param_map = {
    "blocker": {
        "a": ["a"],
        "r": ["r"],
        "g": ["g"],
        "b": ["b"],
        "afrom": ["afrom"],
        "rfrom": ["rfrom"],
        "gfrom": ["gfrom"],
        "bfrom": ["bfrom"],
        "fadetime": ["fadetime", "duration"],
        "block": ["block", "isblock"],
        "style": ["style"],
        "inverse": ["inverse"],
        "initr": ["initr"],
        "image": ["image"],
    },
    "charslot": {
        "slot": ["slot", "charslot"],
        "name": ["name"],
        "duration": [
            "duration",
            "fadetime",
            "duraiton",
            "aduration",
            "duratin",
            "duratio",
            "direction",
            "Duration",
        ],
        "focus": ["focus", "foucs", "ocus"],
        "posfrom": ["posfrom", "posform", "poasfrom"],
        "posto": ["posto", "posTo"],
        "afrom": ["afrom"],
        "ato": ["ato"],
        "action": ["action"],
        "power": ["power"],
        "block": ["block", "isblock", "blocker", "isblocke"],
        "iscopy": ["iscopy", "isCopy"],
        "bstart": ["bstart"],
        "bend": ["bend"],
        "poszoom": ["poszoom"],
        "scale": ["scale"],
    },
    "character": {
        "name": ["name", "nameage"],
        "name2": ["name2"],
        "fadetime": [
            "fadetime",
            "duration",
            "fadeout",
            "time",
            "fadeitme",
            "fadetiem",
            "fadeime",
            "fatetime",
            "fedetime",
            "fadtime",
            "faetime",
        ],
        "block": ["block", "isblock", "blo", "blok"],
        "focus": ["focus", "foucs", "fpcus"],
        "blackstart": ["blackstart", "blackstart1"],
        "blackend": ["blackend", "blackend1"],
        "blackstart2": ["blackstart2"],
        "blackend2": ["blackend2"],
    },
    "showitem": {"image": ["image"]},
    "sticker": {
        "id": ["id"],
        "x": ["x"],
        "y": ["y"],
        "multi": ["multi"],
        "alignment": ["alignment"],
        "size": ["size"],
        "delay": ["delay"],
        "width": ["width"],
        "diration": ["diration"],
        "block": ["block"],
    },
    "playsound": {
        "key": ["key"],
        "loop": ["loop"],
        "channel": ["channel"],
        "volume": ["volume", "voluym", "volum"],
        "delay": ["delay", "Delay", "delai"],
        "fadetime": ["fadetime", "crossfade"],
        "block": ["block"],
    },
    "soundvolume": {
        "volume": ["volume"],
        "channel": ["channel"],
        "fadetime": ["fadetime"],
    },
    "stopsound": {
        "channel": ["channel"],
        "fadetime": ["fadetime", "fedatime", "duration"],
    },
    "playmusic": {
        "intro": ["intro"],
        "key": ["key"],
        "volume": ["volume", "vol7ume"],
        "fadetime": ["fadetime"],
        "crossfade": ["crossfade", "crosstime"],
        "delay": ["delay"],
    },
    "musicvolume": {
        "volume": ["volume"],
        "channel": ["channel"],
        "fadetime": ["fadetime"],
    },
    "stopmusic": {
        "fadetime": [
            "fadetime",
            "faddetime",
            "fadeetime",
            "fdetime",
            "time",
            "crossfade",
        ]
    },
    "curtain": {
        "direction": ["direction"],
        "fillfrom": ["fillfrom"],
        "fillto": ["fillto"],
        "fadetime": ["fadetime"],
        "block": ["block", "isblock"],
    },
    "camerashake": {
        "duration": ["duration"],
        "xstrength": ["xstrength"],
        "ystrength": ["ystrength"],
        "vibration": ["vibrato"],
        "randomness": ["randomness"],
        "fadeout": ["fadeout"],
        "block": ["block"],
    },
    "avgdisplay": {
        "id": ["id"],
        "name": ["name"],
        "style": ["style"],
        "slot": ["slot"],
        "scalex": ["scalex", "scalexto"],
        "scaley": ["scaley", "scaleyto"],
        "entryfrom": ["entryfrom"],
        "entryto": ["entryto"],
        "duration": ["duration"],
        "block": ["block", "isblock"],
        "layer": ["layer"],
        "x": ["x", "xto"],
        "y": ["y", "yto"],
        "afrom": ["afrom"],
        "ato": ["ato"],
    },
    "delay": {
        "time": ["time", "timr", "TIME", "fadetime", "timw", "tinme", "times", "yime"],
    },
    "background": {
        "image": ["image"],
        "screenadapt": ["screenadapt"],
        "fadetime": ["fadetime", "duration", "time"],
        "block": ["block", "isblock"],
        "x": ["x"],
        "y": ["y", "ypos"],
        "xscale": ["xscale", "xScale", "xScaleTo", "xSclae"],
        "yscale": ["yscale", "yScale", "yScaleTo", "ysclae"],
        "width": ["width"],
        "height": ["height"],
    },
    "bgeffect": {
        "name": ["name"],
        "layer": ["layer"],
        "fadetime": ["fadetime", "duration"],
        "x": ["x"],
        "y": ["y"],
        "xto": ["xto"],
        "yto": ["yto"],
        "movetime": ["movetime"],
        "flip": ["flip"],
    },
    "gridbg": {
        "imagegroup": ["imagegroup"],
        "solidwidth": ["solidwidth"],
        "solidheight": ["solidheight"],
        "x": ["x"],
        "y": ["y"],
        "fadetime": ["fadetime"],
        "xscale": ["xScale"],
        "yscale": ["yScale"],
    },
    "largebg": {
        "imagegroup": ["imagegroup", "cggroup"],
        "solidwidth": ["solidwidth"],
        "solidheight": ["solidheight"],
        "x": ["x"],
        "y": ["y"],
        "fadetime": ["fadetime"],
        "xscale": ["xScale"],
        "yscale": ["yScale"],
    },
    "verticalbg": {
        "imagegroup": ["imagegroup", "cggroup"],
        "solidwidth": ["solidwidth"],
        "solidheight": ["solidheight"],
        "x": ["x"],
        "y": ["y"],
        "fadetime": ["fadetime"],
        "xscale": ["xScale"],
        "yscale": ["yScale"],
    },
    "image": {
        "image": ["image"],
        "screenadapt": ["screenadapt"],
        "fadetime": ["fadetime", "duration", "time", "adetime"],
        "block": ["block", "isblock"],
        "x": ["x", "xpos", "xTO", "xto", "xTo"],
        "y": ["y", "ypos", "yTO", "yto", "yTo", "yT"],
        "xfrom": ["xFrom", "xfrom"],
        "yfrom": ["yFrom", "yfrom"],
        "xscale": ["xscale", "xScale", "xScaleTo", "xSclae", "xScaleto", "fxScale"],
        "yscale": ["yscale", "yScale", "yScaleTo", "ysclae", "yScaleto", "yScaleT"],
        "xscalefrom": ["xScaleFrom", "xfromScale"],
        "yscalefrom": ["yScaleFrom", "yfromScale"],
        "width": ["width"],
        "height": ["height"],
        "layer": ["layer"],
    },
    "imagerotate": {
        "image": ["image"],
        "angle": ["angle"],
        "fadetime": ["fadetime"],
        "block": ["block", "isblock"],
    },
    "characteraction": {
        "name": ["name"],
        "type": ["type"],
        "x": ["x", "xpos"],
        "y": ["y", "ypos"],
        "block": ["block", "isblock"],
        "power": ["power", "pwoer"],
        "duration": ["times", "duration", "time"],
        "direction": ["direction"],
    },
    "imagetween": {
        "image": ["image"],
        "screenadapt": ["screenadapt"],
        "duration": ["duration", "fadetime", "time", "adetime"],
        "block": ["block", "isblock"],
        "x": ["x", "xpos", "xTO", "xto", "xTo"],
        "y": ["y", "ypos", "yTO", "yto", "yTo", "yT"],
        "xfrom": ["xFrom", "xfrom"],
        "yfrom": ["yFrom", "yfrom"],
        "xscale": ["xscale", "xScale", "xScaleTo", "xSclae", "xScaleto", "fxScale"],
        "yscale": ["yscale", "yScale", "yScaleTo", "ysclae", "yScaleto", "yScaleT"],
        "xscalefrom": ["xScaleFrom", "xfromScale"],
        "yscalefrom": ["yScaleFrom", "yfromScale"],
        "width": ["width"],
        "height": ["height"],
        "layer": ["layer"],
    },
    "backgroundtween": {
        "image": ["image"],
        "screenadapt": ["screenadapt"],
        "duration": ["duration", "fadetime", "time", "adetime"],
        "block": ["block", "isblock"],
        "x": ["x", "xpos", "xTO", "xto", "xTo"],
        "y": ["y", "ypos", "yTO", "yto", "yTo", "yT"],
        "xfrom": ["xFrom", "xfrom"],
        "yfrom": ["yFrom", "yfrom"],
        "xscale": ["xscale", "xScale", "xScaleTo", "xSclae", "xScaleto", "fxScale"],
        "yscale": ["yscale", "yScale", "yScaleTo", "ysclae", "yScaleto", "yScaleT"],
        "xscalefrom": ["xScaleFrom", "xfromScale"],
        "yscalefrom": ["yScaleFrom", "yfromScale"],
        "width": ["width"],
        "height": ["height"],
        "layer": ["layer"],
    },
    "largebgtween": {
        "duration": ["duration", "fadetime", "time", "adetime"],
        "block": ["block", "isblock"],
        "x": ["x", "xpos", "xTO", "xto", "xTo"],
        "y": ["y", "ypos", "yTO", "yto", "yTo", "yT"],
        "xfrom": ["xFrom", "xfrom"],
        "yfrom": ["yFrom", "yfrom"],
        "xscale": ["xscale", "xScale", "xScaleTo", "xSclae", "xScaleto", "fxScale"],
        "yscale": ["yscale", "yScale", "yScaleTo", "ysclae", "yScaleto", "yScaleT"],
        "xscalefrom": ["xScaleFrom", "xfromScale"],
        "yscalefrom": ["yScaleFrom", "yfromScale"],
        "width": ["width"],
        "height": ["height"],
        "layer": ["layer"],
    },
}
